http://cloga.info/python/2016/08/24/pandas-big-data-tips

In [4]:
import pandas as pd

In [5]:
# input = pd.read_csv("input.csv", chunksize=1000000)

# for i in input:
#     chunk = dosomething(input)
#     chunk.to_csv("output.csv", mode="a", header=False)
    
# input  = pd.read_csv("input.csv", iterator = True)
# while loop:
#     try:
#         chunk = reader.get_chunk(1000000)
#         chunk.to_csv("output.csv", mode="a", header=False)
#     except StopIteration:
#         break

## 读入时处理日期列
我之前都是在数据读入后通过to_datetime函数再去处理日期列，如果数据量较大这又是一个浪费时间的过程，其实在读入数据时，可以通过parse_dates参数来直接指定解析为日期的列。它有几种参数，TRUE的时候会将index解析为日期格式，将列名作为list传入则将每一个列都解析为日期格式

关于to_datetime函数再多说几句，我们拿到的时期格式常常出现一些乱七八糟的怪数据，遇到这些数据to_datimetime函数默认会报错，其实，这些数据是可以忽略的，只需要在函数中将errors参数设置为’ignore’就可以了。

另外，to_datetime就像函数名字显示的，返回的是一个时间戳，有时我们只需要日期部分，我们可以在日期列上做这个修改，datetime_col = datetime_col.apply(lambda x: x.date())，用map函数也是一样的datetime_col = datetime_col.map(lambda x: x.date())

In [8]:
# reg_data = reg_data.sort_values(["uid", "time"])

# reg_data["pre"] = reg_data["time"].shift(1)
# reg_data["uid0"] = reg_data["uid0"].shift(1)
# reg_data["days"] =( reg_data["time"] - reg_data["pre"]).map(lambda x: x.days)

In [10]:
# df= pd.read_csv("SampleData.csv", nrows=5, usecols=["OrderDate","Item", "Total"])
# usecols 指定 读取的列
# nrows 指定读取文件的行数

In [11]:
# reader = pd.read_table("sampledata.csv", chunksize=10, iterator=True)
# chunksize 设置分块的文件行数

In [15]:
chunks = pd.read_csv('game_logs.csv', iterator=True)
chunk = chunks.get_chunk(10)
chunk

,date,number_of_game,day_of_week,v_name,v_league,v_game_number,h_name,h_league,h_game_number,v_score,...,h_player_7_name,h_player_7_def_pos,h_player_8_id,h_player_8_name,h_player_8_def_pos,h_player_9_id,h_player_9_name,h_player_9_def_pos,additional_info,acquisition_info
0,18710504,0,Thu,CL1,na,1,FW1,na,1,0,...,Ed Mincher,7,mcdej101,James McDermott,8,kellb105,Bill Kelly,9,NaN,Y
1,18710505,0,Fri,BS1,na,1,WS3,na,1,20,...,Asa Brainard,1,burrh101,Henry Burroughs,9,berth101,Henry Berthrong,8,HTBF,Y
2,18710506,0,Sat,CL1,na,2,RC1,na,1,12,...,Pony Sager,6,birdg101,George Bird,7,stirg101,Gat Stires,9,NaN,Y
3,18710508,0,Mon,CL1,na,3,CH1,na,1,12,...,Ed Duffy,6,pinke101,Ed Pinkham,5,zettg101,George Zettlein,1,NaN,Y
4,18710509,0,Tue,BS1,na,2,TRO,na,1,9,...,Steve Bellan,5,pikel101,Lip Pike,3,cravb101,Bill Craver,6,HTBF,Y
5,18710511,0,Thu,CH1,na,2,CL1,na,4,18,...,Ezra Sutton,5,carlj102,Jim Carleton,3,bassj101,John Bass,6,NaN,Y
6,18710513,0,Sat,WS3,na,2,CL1,na,5,12,...,Ezra Sutton,5,white104,Elmer White,9,bassj101,John Bass,6,NaN,Y
7,18710513,0,Sat,CH1,na,3,FW1,na,2,14,...,Ed Mincher,7,donnp101,Pete Donnelly,8,kellb105,Bill Kelly,9,NaN,Y
8,18710515,0,Mon,WS3,na,3,FW1,na,3,6,...,Ed Mincher,7,donnp101,Pete Donnelly,9,kellb105,Bill Kelly,8,NaN,Y
9,18710516,0,Tue,TRO,na,2,BS1,na,3,29,...,Fred Cone,7,spala101,Al Spalding,1,jacks101,Sam Jackson,8,HTBF,Y

### 当文件格式相同时，支持多个文件合并处理

In [19]:
# import os

In [23]:
# filelst = os.listdir(path)   ## 返回指定文件夹 包含的文件或文件夹 名字的列表
# dfs = [pd.read_csv(f) for f in filelst ]
# total_df = pd.concat(dfs)  # 将文件合并

In [31]:
name_length = map(len, ["Mary", "Isla", "Sam"])
squares = [map(lambda x: x * x, [0,1,2,3,4])]

In [33]:
# import re
# re.search(regex, string)#在"regex"中查询是否存在"string"，如存在，则返回match这个object，如不存在则返回"None"
# re.sub("yo", "hello", "yo world")#用"hello"替换"yo world"中的"yo"，可用于标准化字符串
# re.findall("[1-2][0-9]{3}", years_string)#在"years_string"中匹配"1000"到"2999"的字符串